# Generated by Django 3.2.20 on 2024-03-28 08:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('BGR', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='username',
        ),
    ]
