# Generated by Django 3.2.20 on 2024-03-31 14:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BGR', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='language_pref_en',
        ),
        migrations.AddField(
            model_name='user',
            name='language_pref_fr',
            field=models.BooleanField(blank=True, default=False, help_text='English is prefered language'),
        ),
    ]
