# Generated by Django 3.2.20 on 2024-03-30 14:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BGR', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='game',
            name='genre',
            field=models.ManyToManyField(default=[], help_text='Genres', max_length=3, to='BGR.Genre'),
        ),
        migrations.AlterField(
            model_name='genre',
            name='name_en',
            field=models.CharField(help_text='Genre name en', max_length=200, unique=True),
        ),
    ]
