# Generated by Django 3.2.20 on 2024-03-30 14:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BGR', '0002_auto_20240330_2328'),
    ]

    operations = [
        migrations.AlterField(
            model_name='game',
            name='genre',
            field=models.ManyToManyField(blank=True, help_text='Genres', max_length=3, to='BGR.Genre'),
        ),
    ]
